INCLUDE(${PLATFORM_DIR}/CommonFlags.cmake)

IF( (${TARGET_PLATFORM} STREQUAL "CYT2B75_M0PLUS") OR (${TARGET_PLATFORM} STREQUAL "CYT2B75_M4") )
    INCLUDE(${PLATFORM_DIR}/Infineon/cyt2b75/FindFlags.cmake)
ELSEIF(${TARGET_PLATFORM} STREQUAL "STM32F4")
    INCLUDE(${PLATFORM_DIR}/STM/stm32f4/FindFlags.cmake)
ENDIF()
