INCLUDE(${PLATFORM_DIR}/CommonFlags.cmake)

IF( (${TARGET_PLATFORM} STREQUAL "CYT2B75_M0PLUS") OR (${TARGET_PLATFORM} STREQUAL "CYT2B75_M4") )
    INCLUDE(${PLATFORM_DIR}/Infineon/cyt2b75/FindFlags.cmake)
ENDIF()
